### ISSUE TITLE
Status of tasks for initial release

### ISSUE THREAD

**Issue by codesections** [tootsuite/flodgatt#65]
This is a tracking issue to sort current tasks into those that *must* be accomplished before initial release, those that can be completed after the initial release, and those that I am not sure whether they are required for initial release. 

#### Pre-release tasks
- [x] Complete refactor for type safety in config (follow-up to #63)
- [x] Unix socket support (#60)
- [x] Add postgres connection pool (#31)
- [x] Add healthcheck API (#67)
- [x] Fix boosts-on-federated-timeline bug (#83)

#### Post-release tasks
- [ ] Update dependencies to unblock future performance, stability, and security fixes
- [ ] Improve test coverage (#61, #42) 
- [x] Improve error handling (#55)
- [x] Create statically-linked binary (#39) 
- [ ] Consider using async-await once it has stabilized  

#### Undetermined  
- [ ] Add SSL support for Postgres (#41)
- [x] Add `WHITELIST_MODE` support (#40)
- [ ] Add configuration variable for `TRUSTED_PROXY_IP` (#23)

@Gargron, any thoughts on whether any of the items in "Undetermined" need to be completed before release?

**Comment by codesections** [comment]
All incomplete actions have been moved their own tracking issues and given appropriate labels.
